# Generated by Django 5.0.4 on 2024-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin_numrut', models.IntegerField(verbose_name='Numero de rut')),
                ('admin_dv', models.CharField(max_length=1, verbose_name='Digito verificador')),
                ('admin_p_nombre', models.CharField(max_length=25, verbose_name='Primer nombre')),
                ('admin_s_nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo Nombre')),
                ('admin_apaterno', models.CharField(max_length=25, verbose_name='Apellido paterno')),
                ('admin_apmaterno', models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido materno')),
                ('admin_fec_nac', models.DateField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('clase_usuario', models.CharField(max_length=50, verbose_name='Nombre de clase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Custom Token',
                'verbose_name_plural': 'Custom Tokens',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('rut_emp', models.IntegerField()),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razon social')),
                ('telefono2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
